# Read the documentation at https://github.com/thephpleague/flysystem-bundle/blob/master/docs/1-getting-started.md
flysystem:
    storages:
        files.storage:
            adapter: 'local'
            options:
                directory: '%env(resolve:DOCUMENTS_PATH)%'
